# Generated by Django 4.2.11 on 2024-05-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_our_home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='nombre_region',
            new_name='name_region',
        ),
    ]
