# Generated by Django 4.2.11 on 2024-05-08 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_our_home', '0002_rename_nombre_region_region_name_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='app_our_home.region'),
        ),
    ]
