# Generated by Django 4.2.11 on 2024-05-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_our_home', '0003_alter_district_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('plot', 'Plot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord')], max_length=20),
        ),
    ]
